version: '3.8'

services:
  db_fastapi:
    image: postgres:15
    env_file:
      - .env
    container_name: db_fastapi
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432" # Porta 5433 para não conflitar com o seu outro banco

  web_fastapi:
    build: .
    env_file:
      - .env
    container_name: web_fastapi
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - .:/code
    ports:
      - "8001:8001" # Porta 8001 para acessar a API
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/furniture_fastapi_db
    depends_on:
      - db_fastapi

  dashboard:
    build: .
    # Alterado para 8501 para não bater com a porta da API
    command: streamlit run dashboard.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - web_fastapi